services:
  - type: web
    name: wewear-backend
    env: docker
    region: frankfurt  # Changed to Frankfurt (EU) region
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/app.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/java/openjdk
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: WEWEAR_DB_URL
        fromDatabase:
          name: wewear_db
          property: connectionString
      - key: WEWEAR_DB_USERNAME
        fromDatabase:
          name: wewear_db
          property: username
      - key: WEWEAR_DB_PASSWORD
        fromDatabase:
          name: wewear_db
          property: password
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: wewear_db
    plan: free
    ipAllowList: [] 